modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "svc"
version = "${version}"
displayName = "SVC Holograms"
authors = "Syconn"
description = '''
A mod that add the Holographic Communicators from Syconn's Star Wars Mod.
'''
#logoFile = ""

[[dependencies.svc]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.svc]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.svc]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
