architectury {
    common rootProject.enabled_platforms.split(',')
}

loom {
    interfaceInjection {
        enableDependencyInterfaceInjection = true
    }
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"
    modImplementation "dev.architectury:architectury:$rootProject.architectury_api_version"
    modCompileOnly("de.maxhenkel.voicechat:voicechat-api:${voicechat_api_version}")
}
